clear;clc;

%Text inside the first box
prompt = {'Name:',...
          'Year of birth:',...
          'Month of birth:',...
          'Date of birth:',...
          'Weight(in Kg):',...
          'Your Height(in Meters)'};
      
%Default answer inside the first box      
defaultanswer = {'Sek Naing Phyo',...
                 '1998',...
                 '9',...
                 '11',...
                 '80',...
                 '1.8'};
             
%Title for the first box             
title = 'Body Measuring Index';

%Size of the first box
numlines = [1 80];

%User Interface of the first box
answer = inputdlg(prompt, title, numlines, defaultanswer);

%Extracting results from the first box
name1 = answer(1);
year = answer(2);
month = answer(3);
date = answer(4);
weight = answer(5);
height = answer(6);

%The two functions to calculate age and BMI
[y, m, d] = calculateage(year, month, date);
bodymeasuringindex = calculate(weight,height);

%Conditions for the BMI

if bodymeasuringindex <= 18.5
    
    prompt1 = {'Hello' cell2mat(name1),...
               'You are' num2str(y) 'years' num2str(m) 'months and' num2str(d) 'days old.',...
               'Your BMI is' num2str(bodymeasuringindex),...
               'You are underweight. Please see a physician to consult your condition.'};
           
elseif (18.5 < bodymeasuringindex) && (bodymeasuringindex <= 25)
    prompt1 = {'Hello' cell2mat(name1),...
               'You are' num2str(y) 'years' num2str(m) 'months and' num2str(d) 'days old.',...
               'Your BMI is' num2str(bodymeasuringindex),...
               'You are healthy.'};
           
elseif (25 < bodymeasuringindex) && (bodymeasuringindex <= 30)
    prompt1 = {'Hello' cell2mat(name1),...
              'You are' num2str(y) 'years' num2str(m) 'months and' num2str(d) 'days old.',...
               'Your BMI is' num2str(bodymeasuringindex),...
               'You are overweight. Start maintaining your body to prevent from potentially dangerous health conditions.'};
           
elseif bodymeasuringindex >= 30
    prompt1 = {'Hello' cell2mat(name1),...
               'You are' num2str(y) 'years' num2str(m) 'months and' num2str(d) 'days old.',...
               'Your BMI is' num2str(bodymeasuringindex),...
               'You are obese. Please see a physician to consult your condition.'};
end

%Produce result
msgbox(prompt1, title);